filebeat.inputs:
- type: log
  paths:
          - /usr/share/filebeat/logs/*.log:ro
  exclude_files: ['\.gz$']

  index: "weblogs-%{+YYYY.MM.dd}"
  enabled: true

output.elasticsearch:
  hosts: ["http://192.168.1.2:9200"]
  username: "elastic"
  password: "elastic"
  

setup.dashboards.enabled: true
setup.kibana.host: "http://192.168.1.2:5601"
